name: 'news_transformations'
version: '1.0.0'
config-version: 2

profile: 'news_transformations'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  news_transformations:
    staging:
      materialized: view
    marts:
      materialized: table
