news_transformations:
  target: dev
  outputs:
    prod:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('DBT_PROJECT_ID') }}"
      dataset: news_data
      location: EU
      keyfile_json:
        "{{ env_var('DBT_SERVICE_ACCOUNT_JSON') }}"
